FROM ubuntu
RUN apt-get update
RUN apt-get install -qy nginx
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
COPY ./nginx/backend.conf /etc/nginx/conf.d/backend.conf
CMD nginx -d